=== sunofsparda/mntlab-xml/task2_1.xsd
<?xml version="1.0"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="vendor" type="xs:string"/>
  <xs:element name="model" type="xs:string" value="[a-zA-Z][a-zA-Z][0-9][0-9][0-9]"/>
  <xs:element name="date" type="xs:string" value="^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d$"/>
  <xs:element name="color" type="xs:string"/>
  <xs:element name="price" type="xs:integer"/>
  <xs:element name="pieces" type="xs:integer"/>
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vendor"/>
        <xs:element ref="model"/>
        <xs:element ref="date"/>
        <xs:element ref="color"/>
        <xs:element ref="price"/>
        <xs:element ref="pieces"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="watch">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="shoes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="headphones">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cars">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mfu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="store">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="watch"/>
        <xs:element ref="shoes"/>
        <xs:element ref="headphones"/>
        <xs:element ref="cars"/>
        <xs:element ref="mfu"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sunofsparda/mntlab-xml/task2_1.xml
<?xml version="1.0"?>

<store schemaLocation="http://localhost:8080/task2_1.xsd" xmlns="http://localhost:8080">
		<watch>
			<item>
				<vendor>Casio</vendor>
				<model>ab123</model>
				<date>01-01-2010</date>
				<color>white</color>
				<price>10</price>
				<pieces>100</pieces>
			</item>
		</watch>

		<shoes>
			<item>
				<vendor>Nike</vendor>
				<model>zx111</model>
				<date>05-05-2015</date>
				<color>blue</color>
				<price>30</price>
				<pieces>50</pieces>
			</item>
		</shoes>

		<headphones>
			<item>
				<vendor>Marshall</vendor>
				<model>qz888</model>
				<date>10-10-2016</date>
				<color>black</color>
				<price>100</price>
				<pieces>5</pieces>
			</item>
		</headphones>

		<cars>
			<item>
				<vendor>Cadillac</vendor>
				<model>Coupe De Ville</model>
				<date>01-07-1959</date>
				<color>white</color>
				<price>99999</price>
				<pieces>1</pieces>
			</item>
		</cars>

		<mfu>
			<item>
				<vendor>HP</vendor>
				<model>1110</model>
				<date>01-01-2008</date>
				<color>grey</color>
				<price>20</price>
				<pieces>0</pieces>
			</item>
		</mfu>
</store>
